Update patch set 9
Patch Set 9:

Most of the static check failures are in files which imported from tf-a project(libfdt) which are ignored from static checks in "platform-ci", i am trying to find if we can ignore those files in tf-a-tests as well.
Apart from that, following are some failures in newly added files, which i think can be fixed or if you want, we can add in "igonre-list".

include/lib/libfdt/libfdt_env_fm.h:22: ERROR: Do not include the paragraph about writing to the Free Software Foundation's mailing address from the sample GPL notice. The FSF has changed addresses in the past, and may do so again. Linux already includes a copy of the GPL.
+ *     License along with this library; if not, write to the Free$

include/lib/libfdt/libfdt_env_fm.h:23: ERROR: Do not include the paragraph about writing to the Free Software Foundation's mailing address from the sample GPL notice. The FSF has changed addresses in the past, and may do so again. Linux already includes a copy of the GPL.
+ *     Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,$

include/lib/libfdt/libfdt_env_fm.h:135: ERROR: code indent should use tabs where possible
+          MAC_OS_X_VERSION_10_7) */$


Errors in : smc_fuzz/include/smcmalloc.h
smc_fuzz/src/smcmalloc.c:166: ERROR: code indent should use tabs where possible
smc_fuzz/src/smcmalloc.c:312: ERROR: trailing whitespace

Patch-set: 9
Reviewer: Gerrit User 1000102 <1000102@8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda>