Update patch set 4
Patch Set 4: -Allow-CI

The static checks fail because checkpatch is complaining about:
tftf/tests/misc_tests/test_pmu_leakage.c:152: ERROR: space prohibited after that '-' (ctx:WxW)
+	evt_cnt = (*read_cntr_f)() - evt_cnt;
 	                           ^
We might want to look into the TFTF scripts for checkpatch to disable this check?

Patch-set: 4
Label: Allow-CI=0