build(clang): introduce clang toolchain support
Only the compiler is switched to clang. The assembler and the
linker are provided  by the GCC toolchain.

clang is used to build TFTF when the base name of the path assigned
to  "CC" variable contains the string 'clang'.

'CROSS_COMPILE' flg is still required and must point to the appropriate
GCC toolchain.

Note:
Compiling TF-A tests with clang toolchain has following
issues and as a result few sections of the code have
been commented or guarded accordingly:

1. error: instruction requires: wfxt

2. error: initializer element is not a compile-time constant
   test_ffa_setup_and_discovery.c:33:11[.uuid = sp_uuids[0]]
   sp_test_ffa.c:38:11:.uuid = sp_uuids[0]

3. For el3_payload target:
   CC      entrypoint.S
LLVM/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/clang\
-nostdinc -ffreestanding -Wa,--fatal-warnings -Werror \
-Iplat/fvp/ -I. -DFVP_MAX_PE_PER_CPU=1 -c entrypoint.S -o \
build/fvp/entrypoint.o

<instantiation>:2:2: error: unknown directive

4. spm/cactus_mm/cactus_mm_tests_system_setup.c:59:19:
   error: instruction requires: fp-armv8
   __asm__ volatile("fmov %0, d0" : "=r" (fp_reg) :: "d0");

* These are the errors encountered while switching to Clang
  compiler. Currently these errors are masked/commented
  to see the overall results.

However few instructions still need assistance from clang
compiler for compiling inline assembly code as wfxt.

Considering all these limitations, this is an introductory
patch to cover the overall codebase.

Issues listed should or will be handled individually on a
case by case basis and should be resolved.

In summary, with this patch, we will be able to compile
TFTF code covering all the targets with below command:

********************************************************
*Build TFTF Aarch64 ( Default Build ) with Clang support
********************************************************
make CC=${CLANG_PATH}/clang \
PLAT=fvp \
CROSS_COMPILE=aarch64-none-elf- \
ARM_ARCH_MINOR=7 \
V=0 tftf

Signed-off-by: Jayanth Dodderi Chidanand <jayanthdodderi.chidanand@arm.com>
Change-Id: I409d11b596dfd50a3d25598679808dd9fcfc51e5